1 FOR I = 1 TO 5: DATA FOR I = 1 TO 5 
2 READ A$: DATA READ A$ 
3 PRINT USING "# &";I;A$;: DATA PRINT USING "# &";I;A$; 4 PRINT CHR$(58);" DATA
";A$: DATA PRINT CHR$(58);" DATA ";A$ 5 NEXT I: DATA NEXT I
